export const project = [
    {
        title: "Project Alpha",
        description: "A project about building a new feature.",
        status: "Ongoing",
        startDate: "2024-01-15",
        endDate: "2024-06-30",
        teamMembers: ["Alice", "Bob", "Charlie"],
    },
    {
        title: "Project Beta",
        description: "A project focused on improving performance.",
        status: "Completed",
        startDate: "2023-05-01",
        endDate: "2023-12-15",
        teamMembers: ["David", "Eve", "Frank"],
    },
    {
        title: "Project Gamma",
        description: "Research and development of new technologies.",
        status: "Ongoing",
        startDate: "2024-03-10",
        endDate: "2024-11-20",
        teamMembers: ["Grace", "Heidi", "Ivan"],
    },
    {
        title: "Project Delta",
        description: "Client project for building a mobile application.",
        status: "Planned",
        startDate: "2024-07-01",
        endDate: "2025-01-31",
        teamMembers: ["Judy", "Karl", "Liam"],
    },
    {
        title: "Project Epsilon",
        description: "Upgrading existing infrastructure and systems.",
        status: "Ongoing",
        startDate: "2024-02-20",
        endDate: "2024-10-15",
        teamMembers: ["Mallory", "Niaj", "Olivia"],
    },
    {
        title: "Project Zeta",
        description: "Marketing campaign for new product launch.",
        status: "Completed",
        startDate: "2023-08-01",
        endDate: "2024-02-28",
        teamMembers: ["Peggy", "Quentin", "Rupert"],
    },
    {
        title: "Project Eta",
        description: "Internal tool development for process automation.",
        status: "Planned",
        startDate: "2024-09-15",
        endDate: "2025-03-30",
        teamMembers: ["Sybil", "Trent", "Uma"],
    },
    {
        title: "Project Theta",
        description: "Customer feedback analysis and reporting.",
        status: "Ongoing",
        startDate: "2024-04-05",
        endDate: "2024-12-10",
        teamMembers: ["Victor", "Wendy", "Xander"],
    },
    {
        title: "Project Iota",
        description: "Website redesign and user experience improvement.",
        status: "Completed",
        startDate: "2023-11-01",
        endDate: "2024-05-15",
        teamMembers: ["Yvonne", "Zach", "Aaron"],
    },
    {
        title: "Project Kappa",
        description: "Data migration to new cloud infrastructure.",
        status: "Ongoing",
        startDate: "2024-06-01",
        endDate: "2024-12-31",
        teamMembers: ["Betty", "Carl", "Diana"],
    }
]